### ISSUE TITLE
snabb lwaftr control reload does not properly reload updated binding-table

### ISSUE THREAD

**Issue by chrgraf** [Igalia/snabbswitch#655]
Dear all,

kindly need help on an impacting issue.

vmx-docker-lwaftr is using the "snabb lwaftr control reload" function to reload an updated binding-table.
This reload is not working correctly and lwaftr will still use the "old" binding-table.

killing snabb and let it freshly load the assigned binding-table does work correctly, which proves that both the old and new binding-table are syntactically correct.

**Version in use**
https://github.com/igalia/snabb/tree/bd3811f74520bb2f7a1fd96fc3291ae64ceeaa94

# reproducing the issue

## steps required - overview
- launch lwaftr
- modify binding-table.s
- perform lwaftr control reload
- check if modified binding-table is in place. issue is reported, because the reload does NOT use the updated binding-table.

## detailed steps

**launching snabb**
```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# ./usr/local/bin/snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --on-a-stick 0000:81:00.1
Warning: No NUMA memory affinity.
Pass --cpu to bind to a CPU and its NUMA node.
loading compiled binding table from ./binding_table.txt.s.o
compiled binding table ./binding_table.txt.s.o is up to date.
```

**checking actual binding-table**
```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# cat binding_table.txt.s
psid_map {
  192.168.20.1 {psid_length=6, shift=10}
  192.168.20.10 {psid_length=6, shift=10}
  192.168.20.11 {psid_length=6, shift=10}
  192.168.20.12 {psid_length=6, shift=10}
  192.168.20.13 {psid_length=6, shift=10}
  192.168.20.14 {psid_length=6, shift=10}
  192.168.20.15 {psid_length=6, shift=10}
  192.168.20.16 {psid_length=5, shift=11}
  192.168.20.2 {psid_length=6, shift=10}
  192.168.20.3 {psid_length=6, shift=10}
  192.168.20.4 {psid_length=6, shift=10}
  192.168.20.5 {psid_length=6, shift=10}
  192.168.20.6 {psid_length=6, shift=10}
  192.168.20.7 {psid_length=6, shift=10}
  192.168.20.8 {psid_length=6, shift=10}
  192.168.20.9 {psid_length=6, shift=10}
}
br_addresses {
  fc00::100,
}
softwires {
  { ipv4=192.168.20.1, psid=1, b4=fc00:200::1, aftr=0 }
  { ipv4=192.168.20.2, psid=1, b4=fc00:200::2, aftr=0 }
  { ipv4=192.168.20.3, psid=1, b4=fc00:200::3, aftr=0 }
  { ipv4=192.168.20.4, psid=1, b4=fc00:200::4, aftr=0 }
  { ipv4=192.168.20.5, psid=1, b4=fc00:200::5, aftr=0 }
  { ipv4=192.168.20.6, psid=1, b4=fc00:200::6, aftr=0 }
  { ipv4=192.168.20.7, psid=1, b4=fc00:200::7, aftr=0 }
  { ipv4=192.168.20.8, psid=1, b4=fc00:200::8, aftr=0 }
  { ipv4=192.168.20.9, psid=1, b4=fc00:200::9, aftr=0 }
  { ipv4=192.168.20.10, psid=1, b4=fc00:200::10, aftr=0 }
  { ipv4=192.168.20.11, psid=1, b4=fc00:200::11, aftr=0 }
  { ipv4=192.168.20.12, psid=1, b4=fc00:200::12, aftr=0 }
  { ipv4=192.168.20.13, psid=1, b4=fc00:200::13, aftr=0 }
  { ipv4=192.168.20.14, psid=1, b4=fc00:200::14, aftr=0 }
  { ipv4=192.168.20.15, psid=1, b4=fc00:200::15, aftr=0 }
  { ipv4=192.168.20.16, psid=1, b4=fc00:200::16, aftr=0 }
  { ipv4=192.168.20.16, psid=2, b4=fc00:200::17, aftr=0 }
}
```

**config**
```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# cat snabbvmx-lwaftr-xe0.conf
hairpinning = false,
binding_table = binding_table.txt.s,
aftr_ipv6_ip = 2001:db8::1,
aftr_ipv4_ip = 192.168.0.2,
aftr_mac_inet_side = 02:2e:80:9e:81:01,
inet_mac = 02:02:02:02:02:02,
aftr_mac_b4_side = 02:2e:80:9e:81:01,
next_hop6_mac = 02:02:02:02:02:02,
ipv4_mtu = 9000,
ipv6_mtu = 9000,
vlan_tagging = false,
policy_icmpv4_incoming = drop,
policy_icmpv4_outgoing = drop,
policy_icmpv6_incoming = drop,
policy_icmpv6_outgoing = drop,
icmpv6_rate_limiter_n_packets = 300000,
icmpv6_rate_limiter_n_seconds = 4,
```

**checking proper operation of the binding-table via scapy**
We see that lwaftr proper encapsulates the IPv4 packet into an lw4o6 tunnel
Later on we will delete this binding-entry, reload the binding-table and see that forwarding for this deleted binding-entry is still active
```
>>> v4=Ether(src='02:00:00:00:00:01', dst='02:2e:80:9e:81:01')/IP(src='10.0.1.100',dst='192.168.20.16')/UDP(dport=4096)
>>> sendp(v4,iface='enp129s0f0')

18:06:34.613911 IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
18:06:34.614452 IP6 fc00::100 > fc00:200::17: IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
```

### **now triggering the issue**
Lets remove all 192.168.20.16 entries from the binding table (so removing 3 lines).
Below is the diff between old and new binding-table.s

```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# diff binding_table.txt.s binding_table.txt.s.org
8a9
>   192.168.20.16 {psid_length=5, shift=11}
36a38,39
>   { ipv4=192.168.20.16, psid=1, b4=fc00:200::16, aftr=0 }
>   { ipv4=192.168.20.16, psid=2, b4=fc00:200::17, aftr=0 }

>>> updated binding-table
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# cat binding_table.txt.s
psid_map {
  192.168.20.1 {psid_length=6, shift=10}
  192.168.20.10 {psid_length=6, shift=10}
  192.168.20.11 {psid_length=6, shift=10}
  192.168.20.12 {psid_length=6, shift=10}
  192.168.20.13 {psid_length=6, shift=10}
  192.168.20.14 {psid_length=6, shift=10}
  192.168.20.15 {psid_length=6, shift=10}
  192.168.20.2 {psid_length=6, shift=10}
  192.168.20.3 {psid_length=6, shift=10}
  192.168.20.4 {psid_length=6, shift=10}
  192.168.20.5 {psid_length=6, shift=10}
  192.168.20.6 {psid_length=6, shift=10}
  192.168.20.7 {psid_length=6, shift=10}
  192.168.20.8 {psid_length=6, shift=10}
  192.168.20.9 {psid_length=6, shift=10}
}
br_addresses {
  fc00::100,
}
softwires {
  { ipv4=192.168.20.1, psid=1, b4=fc00:200::1, aftr=0 }
  { ipv4=192.168.20.2, psid=1, b4=fc00:200::2, aftr=0 }
  { ipv4=192.168.20.3, psid=1, b4=fc00:200::3, aftr=0 }
  { ipv4=192.168.20.4, psid=1, b4=fc00:200::4, aftr=0 }
  { ipv4=192.168.20.5, psid=1, b4=fc00:200::5, aftr=0 }
  { ipv4=192.168.20.6, psid=1, b4=fc00:200::6, aftr=0 }
  { ipv4=192.168.20.7, psid=1, b4=fc00:200::7, aftr=0 }
  { ipv4=192.168.20.8, psid=1, b4=fc00:200::8, aftr=0 }
  { ipv4=192.168.20.9, psid=1, b4=fc00:200::9, aftr=0 }
  { ipv4=192.168.20.10, psid=1, b4=fc00:200::10, aftr=0 }
  { ipv4=192.168.20.11, psid=1, b4=fc00:200::11, aftr=0 }
  { ipv4=192.168.20.12, psid=1, b4=fc00:200::12, aftr=0 }
  { ipv4=192.168.20.13, psid=1, b4=fc00:200::13, aftr=0 }
  { ipv4=192.168.20.14, psid=1, b4=fc00:200::14, aftr=0 }
  { ipv4=192.168.20.15, psid=1, b4=fc00:200::15, aftr=0 }
}
```

**_so the new binding-table does not contain any "192.168.20.16" and as such the reloaded binding-table shall not encapsulate the previous shown packet_**

shortly  reloading the binding-table. But first check which PID to use..

```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# ps -ef | grep snabb
root     111633 103834  0 18:02 pts/25   00:00:00 ./usr/local/bin/snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --on-a-stick 0000:81:00.1
root     111634 111633 99 18:02 pts/25   00:11:19 ./usr/local/bin/snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --on-a-stick 0000:81:00.1
root     111660 103339  0 18:13 pts/6    00:00:00 grep snabb
```

making sure we use the correct PID 111634

```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# ./usr/local/bin/snabb lwaftr query 111633
No such Snabb instance: 111633
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# ./usr/local/bin/snabb lwaftr query 111634
lwAFTR operational counters (non-zero)
drop-all-ipv4-iface-bytes:          3,529
drop-all-ipv4-iface-packets:        47
drop-no-dest-softwire-ipv4-bytes:   3,529
drop-no-dest-softwire-ipv4-packets: 47
drop-out-by-policy-icmpv4-packets:  47
in-ipv4-bytes:                      3,709
in-ipv4-frag-reassembly-unneeded:   64
in-ipv4-packets:                    50
in-ipv6-frag-reassembly-unneeded:   123
memuse-ipv4-frag-reassembly-buffer: 463,571,780
memuse-ipv6-frag-reassembly-buffer: 464,727,376
out-ipv4-frag-not:                  14
out-ipv6-bytes:                     300
out-ipv6-frag-not:                  3
out-ipv6-packets:                   3
```

now reloading PID 111634

```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# ./usr/local/bin/snabb lwaftr control 111634 reload
```
output of snabb

```
Reloading binding table.
loading compiled binding table from ./binding_table.txt.s.o
compiled binding table ./binding_table.txt.s.o is out of date; recompiling.
loading source binding table from ./binding_table.txt.s
```

### lwaftr is still accepting the binding-entry for 192.168.20.16 which was deleted in the actual binding-table.s, hence this issue.

```
root@psal-holoplan1:/storage/training/vmx-docker-lwaftr/tests/tmp1# sudo tcpdump -n -i enp129s0f0 not port 179
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp129s0f0, link-type EN10MB (Ethernet), capture size 262144 bytes
18:16:53.881890 IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
18:16:53.882390 IP6 fc00::100 > fc00:200::17: IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
```

issue is reproducible. kindly have it addressed.

thanks

christian

**Comment by mwiget** [comment]
This used to work in the past, but got broken by the introduction of BTLookupQueue in
https://github.com/Igalia/snabb/commit/39cc6e0195fff0ca2396a1d3c5a4ea344a9650d4:
When receiving a reload message, the inet and hairpin lookup table don't get updated, only the binding table. 
Because we are still using the pre-yang lwaftr version, I have a patch based on the sub module version documented above, but can't simply create a pull request.

My patch can be found here: https://github.com/mwiget/snabb/commit/1c907062e7721cc75a8183b3232b4da58e34f16c and is applied in branch: https://github.com/mwiget/snabb/tree/bt-reload-fix

Updated vmx-docker-lwaftr to version v1.1.18, linking snabb to the bt-reload-fix 

May I suggest to create a branch on igalia based on https://github.com/igalia/snabb/tree/bd3811f74520bb2f7a1fd96fc3291ae64ceeaa94, so I can create a pull request into that branch? It will take some time to upgrade the container to the final yang based version of snabb with dynamic binding table updates ...

**Comment by dpino** [comment]
Hi @chrgraf, @mwiget 

I just published a new tag "lwaftr-snabbvmx-v1.2" based on the requested commit:

```
$ git log -1 igalia/lwaftr-snabbvmx-v1.2
commit bd3811f74520bb2f7a1fd96fc3291ae64ceeaa94
Merge: f08390b 9856da7
Author: Diego Pino <dpino@users.noreply.github.com>
Date:   Thu Oct 27 17:28:09 2016 +0200

    Merge pull request #513 from dpino/add-test-ipv4-cache-trigger
 
    Add unit test for ipv4_cache_trigger
```

**Comment by chrgraf** [comment]
Hi Marcel,

using v1.1.18 and is still not yet working. The interesting thing is, that the dump-bindingtable function does indeed show the correct binding-table, but somehow its not active.

**version 1.1.18**
```
juniper@psal-holoplan1:~$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
8b1fc318f034        vmx-docker-lwaftr:v1.1.17   "/usr/bin/dumb-init /"   33 minutes ago      Up 33 minutes       8700/tcp            1_1_18-training-lwaftr

juniper@psal-holoplan1:/storage/training/vmx-docker-lwaftr$ git log
commit 3db5714dfe80b7ecc755616ca81f676e75712f6c
Author: Marcel Wiget <mwiget@juniper.net>
Date:   Thu Dec 8 18:57:06 2016 +0100

    moved snabb to bt-reload-fix on github.com/mwiget/snabb.git

```

Used same procedure as before, edit via vi the binding-table on the vCP and add last two 192.168.20.16 entries.

getting the changes activated via commit

```
root@1_1_17-lwaftr:/var/home/lab # vi /var/db/scripts/commit/bindingtable
process_new_config
psid for xe0 is 1541
global binding table file bindingtable
reading binding file bindingtable
bindingtable br_address 0 is fc00::100
bindingtable ignoring line
compare files bindingtable.s.new bindingtable.s
Binding table bindingtable.s changed. Recompiling ...done.

global binding table file bindingtable reload=1
--------> snabb xe0:
reading binding file bindingtable
bindingtable br_address 0 is fc00::100
bindingtable ignoring line
compare files bindingtable.s.new bindingtable.s
no change detected between bindingtable.s.new bindingtable.s
psid of snabb process for xe0 is 1541
forcing binding table reload for xe0 (1541)
Reloading binding table.
loading compiled binding table from ./bindingtable.s.o
compiled binding table ./bindingtable.s.o is out of date; recompiling.
loading source binding table from ./bindingtable.s
cleanup
```
the binding-table as in /tmp
```
root@8b1fc318f034:/tmp# cat bindingtable.s
psid_map {
  192.168.20.1 {psid_length=6, shift=10}
  192.168.20.10 {psid_length=6, shift=10}
  192.168.20.11 {psid_length=6, shift=10}
  192.168.20.12 {psid_length=6, shift=10}
  192.168.20.13 {psid_length=6, shift=10}
  192.168.20.14 {psid_length=6, shift=10}
  192.168.20.15 {psid_length=6, shift=10}
  192.168.20.16 {psid_length=5, shift=11}  <<<< sending traffic to this one
  192.168.20.2 {psid_length=6, shift=10}
  192.168.20.3 {psid_length=6, shift=10}
  192.168.20.4 {psid_length=6, shift=10}
  192.168.20.5 {psid_length=6, shift=10}
  192.168.20.6 {psid_length=6, shift=10}
  192.168.20.7 {psid_length=6, shift=10}
  192.168.20.8 {psid_length=6, shift=10}
  192.168.20.9 {psid_length=6, shift=10}
}
br_addresses {
  fc00::100,
}
softwires {
  { ipv4=192.168.20.1, psid=1, b4=fc00:200::1, aftr=0 }
  { ipv4=192.168.20.2, psid=1, b4=fc00:200::2, aftr=0 }
  { ipv4=192.168.20.3, psid=1, b4=fc00:200::3, aftr=0 }
  { ipv4=192.168.20.4, psid=1, b4=fc00:200::4, aftr=0 }
  { ipv4=192.168.20.5, psid=1, b4=fc00:200::5, aftr=0 }
  { ipv4=192.168.20.6, psid=1, b4=fc00:200::6, aftr=0 }
  { ipv4=192.168.20.7, psid=1, b4=fc00:200::7, aftr=0 }
  { ipv4=192.168.20.8, psid=1, b4=fc00:200::8, aftr=0 }
  { ipv4=192.168.20.9, psid=1, b4=fc00:200::9, aftr=0 }
  { ipv4=192.168.20.10, psid=1, b4=fc00:200::10, aftr=0 }
  { ipv4=192.168.20.11, psid=1, b4=fc00:200::11, aftr=0 }
  { ipv4=192.168.20.12, psid=1, b4=fc00:200::12, aftr=0 }
  { ipv4=192.168.20.13, psid=1, b4=fc00:200::13, aftr=0 }
  { ipv4=192.168.20.14, psid=1, b4=fc00:200::14, aftr=0 }
  { ipv4=192.168.20.15, psid=1, b4=fc00:200::15, aftr=0 }
  { ipv4=192.168.20.16, psid=1, b4=fc00:200::16, aftr=0 }  <<<< sending traffic to this one
  { ipv4=192.168.20.16, psid=2, b4=fc00:200::17, aftr=0 }
}
```

dumping the binding-table
```
root@8b1fc318f034:/tmp# snabb lwaftr control 397 dump-configuration
lab@1_1_17-lwaftr# Dump lwAFTR configuration: '/tmp/lwaftr-1481239011.conf'
Dumping lwAFTR binding table...
Binding table dumped to /tmp/binding-table-1481239011.txt.

root@8b1fc318f034:/tmp# cat /tmp/lwaftr-1481239011.conf
aftr_ipv4_ip = 192.168.0.2
aftr_ipv6_ip = 2001:db8::1
aftr_mac_b4_side = 02:2e:80:9e:81:01
aftr_mac_inet_side = 02:2e:80:9e:81:01
binding_table = ./bindingtable.s
hairpinning = false
icmpv4_rate_limiter_n_packets = 600000
icmpv4_rate_limiter_n_seconds = 2
icmpv6_rate_limiter_n_packets = 300000
icmpv6_rate_limiter_n_seconds = 4
inet_mac = 02:02:02:02:02:02
ipv4_mtu = 9000
ipv6_mtu = 9000
max_fragments_per_reassembly_packet = 40
max_ipv4_reassembly_packets = 20000
max_ipv6_reassembly_packets = 20000
next_hop6_mac = 02:02:02:02:02:02
policy_icmpv4_incoming = DROP
policy_icmpv4_outgoing = DROP
policy_icmpv6_incoming = DROP
policy_icmpv6_outgoing = DROP
vlan_tagging = falseroot@8b1fc318f034:/tmp# cat /tmp/binding-table-1481239011.txt
psid_map {
  192.168.20.1-192.168.20.15 { psid_length=6, shift=10  }
  192.168.20.16 { psid_length=5, shift=11  }
}

br_addresses {
  fc00::100
}

softwires {
  { ipv4=192.168.20.4, psid=1, b4=fc00:200::4 }
  { ipv4=192.168.20.14, psid=1, b4=fc00:200::14 }
  { ipv4=192.168.20.2, psid=1, b4=fc00:200::2 }
  { ipv4=192.168.20.16, psid=2, b4=fc00:200::17 }
  { ipv4=192.168.20.5, psid=1, b4=fc00:200::5 }
  { ipv4=192.168.20.15, psid=1, b4=fc00:200::15 }
  { ipv4=192.168.20.1, psid=1, b4=fc00:200::1 }
  { ipv4=192.168.20.3, psid=1, b4=fc00:200::3 }
  { ipv4=192.168.20.10, psid=1, b4=fc00:200::10 }
  { ipv4=192.168.20.8, psid=1, b4=fc00:200::8 }
  { ipv4=192.168.20.11, psid=1, b4=fc00:200::11 }
  { ipv4=192.168.20.6, psid=1, b4=fc00:200::6 }
  { ipv4=192.168.20.12, psid=1, b4=fc00:200::12 }
  { ipv4=192.168.20.9, psid=1, b4=fc00:200::9 }
  { ipv4=192.168.20.16, psid=1, b4=fc00:200::16 }
  { ipv4=192.168.20.7, psid=1, b4=fc00:200::7 }
  { ipv4=192.168.20.13, psid=1, b4=fc00:200::13 }
}
```

according the the binding-table this packet shall match it and get encapsulated
```
01:18:56.486026 IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
01:18:58.629928 IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
```

**to make it working again killing the snabb PID is required**
```
root@8b1fc318f034:/tmp# kill 397

lab@1_1_17-lwaftr# launch snabbvmx for xe0 on cpu 22 (node 1) after 0 seconds ...
numactl --membind=1 --physcpubind=22 /snabb snabbvmx lwaftr --conf snabbvmx-lwaftr-xe0.cfg --id xe0 --pci 0000:81:00.1 --mac 02:2e:80:9e:81:01 --sock %s.socket
loading compiled binding table from ./bindingtable.s.o
compiled binding table ./bindingtable.s.o is up to date.
Hairpinning: no
nic_xe0 network ether 02:2e:80:9e:81:01 mtu 9014
IPv6 fragmentation and reassembly: no
IPv4 fragmentation and reassembly: no
lwAFTR service: enabled
nh_fwd6: cache_refresh_interval set to 1 seconds
loading compiled binding table from ./bindingtable.s.o
compiled binding table ./bindingtable.s.o is up to date.
nh_fwd4: cache_refresh_interval set to 1 seconds
Ingress drop monitor: flush (threshold: 100000 packets; wait: 20 seconds; interval: 1.00 seconds)
Get features 0x18428001
 VIRTIO_F_ANY_LAYOUT VIRTIO_NET_F_MQ VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
vhost_user: Read cached features (0x10028001) from /tmp/vhost_features_xe0.socket
Set features 0x10028001
 VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
rxavail = 320 rxused = 320
rxavail = 307 rxused = 307
```

after killing snabb it does work
```
01:20:54.133883 IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
01:20:54.134407 IP6 fc00::100 > fc00:200::17: IP 10.0.1.100.53 > 192.168.20.16.4096: [|domain]
```

If you please can have a look.


thanks

christian

**Comment by mwiget** [comment]
@dpino I don't think I can create a pull request to a tag, can I? Tags are just pointers to a specific commit IMHO. If correct, can you create a branch instead? It will be a while, until I can migrate to the latest lwaftr. This will require significant changes in snabbvmx, particularly around handling the config file and binding table.

**Comment by dpino** [comment]
@mwiget Yes, that's correct, my mistake. I created a new "lwaftr-snabbvmx" remote branch with bd3811f74520bb2f7a1fd96fc3291ae64ceeaa94 as tip. Should be possible to create a PR to that branch now.

There are other commits that are currently in "lwaftr" branch that fix issues in snabbvmx that need to be backported. I will create a backport PR for those commits too.

**Comment by chrgraf** [comment]
Dear all,

I have been verifying Marcels 1.1.19 container "git clone --recursive -b v1.1.19 https://github.com/juniper/vmx-docker-lwaftr".

Using this container the issue is solved properly.

```
lab@1_1_17-lwaftr#` commit
check for config change...
commit complete

[edit]
lab@1_1_17-lwaftr# getting file bindingtable from 128.0.0.1 ...
done
snabbvmx_manager: updated config for snabbvmx!
process_new_config
psid for xe0 is 1562
global binding table file bindingtable
reading binding file bindingtable
bindingtable br_address 0 is fc00::100
bindingtable ignoring line
compare files bindingtable.s.new bindingtable.s
Binding table bindingtable.s changed. Recompiling ...done.

global binding table file bindingtable reload=1
--------> snabb xe0:
reading binding file bindingtable
bindingtable br_address 0 is fc00::100
bindingtable ignoring line
compare files bindingtable.s.new bindingtable.s
no change detected between bindingtable.s.new bindingtable.s
psid of snabb process for xe0 is 1562
forcing binding table reload for xe0 (1562)
Reloading binding table.
loading compiled binding table from ./bindingtable.s.o
compiled binding table ./bindingtable.s.o is out of date; recompiling.
loading source binding table from ./bindingtable.s
cleanup
```

Editing the binding-table via vi on the routing-engine and then "commit" the config properly reloads the updated binding-table.

closing the issue as being solved

thanks

christian
